### PR TITLE
Add Docusaurus Documentation Page

### PR DESCRIPTION
**Pull request by marcchataigner**
Fixes # .

Changes proposed in this pull request:
-
-
-

@consento-org/maintainer

### CODE REVIEW

**Comment by martinheidegger** [comment]
The error in the build process is caused by the bottom link (/blocks) pointing to nowhere.

**Review by martinheidegger — CHANGES_REQUESTED** [review]
The building blocks, while relevant for building consento, are not done and as such probably not helpful as documentation. But anyways, the change of the url from `/blocks` is breaking the build and will need a redirect if you insist on moving it.

**Comment by marcchataigner** [comment]
@martinheidegger I updated the broken link in the footer (blocks) and in the nabber (teams)

**Comment by marcchataigner** [comment]
@martinheidegger I apologize, some checks related with the plugin were not successful here...  May I let you have a look?  (when you have time, not hurry)  I apologize for that

**Comment by martinheidegger** [comment]
Really? It looks like it works:

Screen Shot 2021-05-07 at 16 51 35

**Review by martinheidegger — APPROVED** [review]
Okay, redirect is in, okay to me.

**Comment by marcchataigner** [comment]
@martinheidegger oh, great  :-)  (the 2 lines above were marked with a red cross, so I thought it was problem...)

**Pull request merged**
